// A small curated list of short, friendly, easy-to-type dictionary words used to
// pre-fill the "new workspace" name so you can just hit Enter and land in a fresh
// workspace without naming it. randomWorkspaceName() picks one that isn't already
// taken; if every word collides it falls back to "<word>-<n>".
const WORDS = [
  "amber",
  "anchor",
  "apex",
  "arbor",
  "aspen",
  "atlas",
  "aurora",
  "basil",
  "beacon",
  "birch",
  "bishop",
  "bloom",
  "breeze",
  "cabin",
  "canyon",
  "cedar",
  "cinder",
  "cirrus",
  "clover",
  "cobalt",
  "comet",
  "coral",
  "cove",
  "crest",
  "cypress",
  "dapple",
  "dawn",
  "delta",
  "drift",
  "dune",
  "ember",
  "fable",
  "falcon",
  "fern",
  "finch",
  "flint",
  "forge",
  "frost",
  "garnet",
  "glade",
  "grove",
  "harbor",
  "haven",
  "hazel",
  "heron",
  "indigo",
  "ivory",
  "jade",
  "juniper",
  "kelp",
  "lagoon",
  "lark",
  "ledge",
  "lichen",
  "lilac",
  "lotus",
  "lumen",
  "maple",
  "marsh",
  "meadow",
  "mesa",
  "mica",
  "mint",
  "mirth",
  "moss",
  "nectar",
  "nimbus",
  "oasis",
  "ochre",
  "olive",
  "onyx",
  "opal",
  "orbit",
  "otter",
  "pebble",
  "pine",
  "plume",
  "quartz",
  "quill",
  "raven",
  "reef",
  "ridge",
  "river",
  "rowan",
  "saffron",
  "sage",
  "sable",
  "shale",
  "shore",
  "slate",
  "sparrow",
  "spruce",
  "summit",
  "tamarind",
  "thistle",
  "thorn",
  "tidal",
  "topaz",
  "umber",
  "valley",
  "verdant",
  "vesper",
  "willow",
  "wisp",
  "zephyr",
]

// Pick a random workspace name not present in `taken` (a set of existing,
// lower-cased workspace titles). Tries each shuffled word once; if all are taken,
// appends an incrementing suffix to a random word so it's still unique.
export function randomWorkspaceName(taken: Set<string> = new Set()): string {
  const lower = new Set(Array.from(taken, (t) => t.toLowerCase()))
  const order = [...WORDS].sort(() => Math.random() - 0.5)
  for (const w of order) if (!lower.has(w)) return w
  const base = order[0]
  for (let n = 2; ; n++) {
    const candidate = `${base}-${n}`
    if (!lower.has(candidate)) return candidate
  }
}
